services:
  - type: web
    name: devgenie-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
